name: Scraper de Convocação EBSERH

on:
  schedule:
    - cron: '0 21 * * *'  # Executa diariamente às 09:00 BRT (12:00 UTC)
  workflow_dispatch:       # Permite execução manual

permissions:
  contents: write

jobs:
  scraper:
    name: Executar scraper de concursos
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar scraper
        run: python main.py
        env:
          TOKEN_BOT: ${{ secrets.TOKEN_BOT }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Configurar Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Verificar mudanças e fazer commit
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add urls_verificadas.txt
            git commit -m "Atualizar URLs verificadas - $(date '+%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "Nenhuma mudança detectada"
          fi
